name: auth
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  audioplayers: ^5.2.1
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  firebase_core:
  firebase_auth:
  flutter_tts: ^3.7.0
  cloud_firestore:
  sqflite: ^2.2.0
  path: ^1.8.3
  supabase_flutter: ^2.8.3
  cupertino_icons: ^1.0.6
  flutter_bloc:
  dio:
  get_it:
  dartz:
  logger:
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/images/starter-img.png
    - lib/images/starter-img-setting.png
    - lib/icons/ic-setting.png
    - lib/icons/ic-report.png
    - lib/icons/ic-complaint.svg
    - lib/icons/ic-error.png
    - lib/icons/ic-people.png
    - lib/icons/ic-add.png
    - lib/icons/ic-audio.png
    - lib/icons/ic-back.svg


    - lib/images/devicon_google.svg
    - lib/images/logos_facebook.svg
    - lib/images/logos_twitter.svg
    - lib/icons/icons8-bell.svg
    - lib/icons/ic-flashcard.png
    - lib/icons/ic-reading.png
    - lib/icons/ic-lock.svg
    - lib/icons/ic-home.svg
    - lib/icons/ic-journey.svg
    - lib/icons/ic-profile.svg
    - lib/icons/ic-circle.svg
    - lib/icons/ic-graph.svg
    - lib/icons/ic-homecard.png
    - lib/icons/ic-close.svg
