name: auth
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter_svg: ^2.0.5
  audioplayers: ^5.2.1
  flutter:
    sdk: flutter
  emoji_picker_flutter: ^1.6.3
  image_picker: ^1.0.4
  record: ^4.4.4
  permission_handler: ^11.0.1
  file_picker: ^6.1.1
  fl_chart: ^0.70.2
  firebase_core:
  firebase_auth:
  flutter_tts: ^3.7.0
  cloud_firestore:
  sqflite: ^2.2.0
  path: ^1.8.3
  supabase_flutter: ^2.8.3
  cupertino_icons: ^1.0.6
  flutter_bloc:
  dio:
  get_it:
  dartz:
  logger:
  shared_preferences:
  flutter_calendar_carousel: ^2.4.4
  google_fonts: ^6.2.1
  percent_indicator: ^4.2.3
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/images/starter-img.png
    - lib/images/starter-img-setting.png
    - lib/icons/ic-setting.png
    - lib/icons/ic-report.png
    - lib/icons/ic-complaint.svg
    - lib/icons/ic-error.png
    - lib/icons/ic-people.png
    - lib/icons/ic-add.png
    - lib/icons/ic-audio.png
    - lib/icons/ic-back.svg
    - lib/images/devicon_google.svg
    - lib/images/logos_facebook.svg
    - lib/images/logos_twitter.svg
    - lib/images/shiba.jpg
    - lib/icons/icons8-bell.svg
    - lib/icons/ic-flashcard.png
    - lib/icons/ic-reading.png
    - lib/icons/ic-lock.svg
    - lib/icons/ic-home.svg
    - lib/icons/ic-journey.svg
    - lib/icons/ic-profile.svg
    - lib/icons/ic-circle.svg
    - lib/icons/ic-graph.svg
    - lib/icons/ic-homecard.png
    - lib/icons/ic-close.svg
