// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIwtHztAszyFr8h_CSHyO0qoBzEQIlXe8',
    appId: '1:183771054572:web:39f4adf924bddb14e1c0c9',
    messagingSenderId: '183771054572',
    projectId: 'nckh-c7b76',
    authDomain: 'nckh-c7b76.firebaseapp.com',
    storageBucket: 'nckh-c7b76.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb6Xjxc73Uv2J1F6iY-4parB0pSQoF5eE',
    appId: '1:183771054572:android:00d8590169915017e1c0c9',
    messagingSenderId: '183771054572',
    projectId: 'nckh-c7b76',
    storageBucket: 'nckh-c7b76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARii0-aK5Ay4OLJZVKgMOb5FP4vw-tYnI',
    appId: '1:183771054572:ios:47dd0aa2533d5cbce1c0c9',
    messagingSenderId: '183771054572',
    projectId: 'nckh-c7b76',
    storageBucket: 'nckh-c7b76.firebasestorage.app',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARii0-aK5Ay4OLJZVKgMOb5FP4vw-tYnI',
    appId: '1:183771054572:ios:47dd0aa2533d5cbce1c0c9',
    messagingSenderId: '183771054572',
    projectId: 'nckh-c7b76',
    storageBucket: 'nckh-c7b76.firebasestorage.app',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIwtHztAszyFr8h_CSHyO0qoBzEQIlXe8',
    appId: '1:183771054572:web:5a14622d566ebe60e1c0c9',
    messagingSenderId: '183771054572',
    projectId: 'nckh-c7b76',
    authDomain: 'nckh-c7b76.firebaseapp.com',
    storageBucket: 'nckh-c7b76.firebasestorage.app',
  );
}
