// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeLZ21eeCfllbfVFKLL3Tt0TLhfDL86yA',
    appId: '1:1057013810704:android:fa2e0b2cf4a5591946ac95',
    messagingSenderId: '1057013810704',
    projectId: 'nckh-ieltslearningapp',
    storageBucket: 'nckh-ieltslearningapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEHMVRm5H7KhG93gEv6utLrLKK8wDjVlo',
    appId: '1:1057013810704:ios:83ec517b4558550946ac95',
    messagingSenderId: '1057013810704',
    projectId: 'nckh-ieltslearningapp',
    storageBucket: 'nckh-ieltslearningapp.firebasestorage.app',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEHMVRm5H7KhG93gEv6utLrLKK8wDjVlo',
    appId: '1:1057013810704:ios:83ec517b4558550946ac95',
    messagingSenderId: '1057013810704',
    projectId: 'nckh-ieltslearningapp',
    storageBucket: 'nckh-ieltslearningapp.firebasestorage.app',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkpF3YhytCcUrdTixEXiPwjFDd1X5xIV8',
    appId: '1:1057013810704:web:199a7c7683acfdab46ac95',
    messagingSenderId: '1057013810704',
    projectId: 'nckh-ieltslearningapp',
    authDomain: 'nckh-ieltslearningapp.firebaseapp.com',
    storageBucket: 'nckh-ieltslearningapp.firebasestorage.app',
  );
}
